# Generated by Django 3.0.4 on 2020-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todays_trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comany_symbol', models.CharField(max_length=64, unique=True)),
                ('company_name', models.CharField(max_length=64, unique=True)),
                ('price_data', models.FloatField(max_length=64)),
                ('change', models.FloatField(max_length=64)),
                ('change_in_percentage', models.FloatField(max_length=64)),
                ('volume', models.IntegerField(max_length=64)),
                ('Avgvol_In3Month', models.IntegerField(max_length=64)),
                ('Market_cap', models.CharField(max_length=64)),
                ('PE_ratio', models.CharField(max_length=64)),
            ],
        ),
    ]
