# Generated by Django 3.0.4 on 2020-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todays_trading',
            name='Avgvol_In3Month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='todays_trading',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
