# Generated by Django 3.0.4 on 2020-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_auto_20200330_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcf', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='todays_trading',
            new_name='Todays',
        ),
    ]
