# Generated by Django 3.0.4 on 2020-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_auto_20200330_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todays',
            name='change_in_percentage',
            field=models.IntegerField(),
        ),
    ]
