# Generated by Django 3.0.4 on 2020-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_auto_20200330_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todays',
            name='volume',
            field=models.CharField(max_length=64),
        ),
    ]
