# Generated by Django 3.0.4 on 2020-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_auto_20200330_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todays',
            name='Comany_symbol',
            field=models.CharField(max_length=64),
        ),
    ]
